AWSTemplateFormatVersion: 2010-09-09

Description: An IAM user that can publish to the S3 Multipart Uploader error SNS topic.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Parameters:
      - UserPassword

Parameters:
  UserPassword:
    Type: String
    NoEcho: true
    Description: The password for the administrator IAM user.
    ConstraintDescription: must conform to this AWS account's password policy, if any.

Resources:
  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: s3-multipart-uploader-errors
      Subscription:
      - # Danware support group
        Protocol: email
        Endpoint: support@danwarecreations.com
  MainUser:
    Type: AWS::IAM::User
    Properties:
      UserName: s3-multipart-uploader
      Path: /s3-multipart-uploader/
      LoginProfile:
        Password: !Ref UserPassword
        PasswordResetRequired: false
      Policies:
      - # SNS publish permissions
        PolicyName: S3MultipartUploader
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Sid: 1
            Effect: Allow
            Action: sns:Publish
            Resource: !Ref ErrorTopic

Outputs:
  ErrorTopic:
    Value: !GetAtt ErrorTopic.TopicName
    Description: TopicName of the SNS topic to which S3 Mulitpart Uploader errors will be published
  MainUser:
    Value: !Ref MainUser
    Description: UserName of the IAM user that S3 Multipart Uploader will use to publish to SNS